(function(oq,po){///*

function e(a,b,c,f,d){b||(b="&");c||(c="=");var g=[];h(a,function(a,b){a&&"object"===typeof a?a=e(a,";",":",!0,!0):a&&"string"===typeof a?d&&(a='"'+encodeURIComponent(a)+'"'):"boolean"===typeof a&&(a=String(a));a&&(f&&(b='"'+encodeURIComponent(b)+'"'),g.push(b+c+a))});return g.join(b)}
function l(a,b){var c=e(a,null,null,!1,!0),f="?pk="+a.B,f=f+("string"===typeof b?"&"+b:""),d;d=window.XDomainRequest?new window.XDomainRequest:window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");f=(location.protocol.match("http")?location.protocol:"http:")+"//i.konduto.com/v1"+f;d.open("POST",f,!0);try{d.send(c)}catch(g){}}function aa(){function a(){return(Math.random().toString(16)+"000000000").substr(2,8)}return a()+a()+a()+a()+a()}
function m(a){return a?"object"===typeof a&&"number"===typeof a.t:!1}function n(a){if(m(a))return a;var b;try{if(!window.JSON)throw 0;b=JSON.parse(a)}catch(c){b=null}if(!b)if(a=a.split(";"),0<a.length)b={},h(a,function(a){var c,g=b;c=a.split("=");2==c.length&&(a=c[0],c=c[1],"t"==a&&(c=parseInt(c)),g[a]=c);b=g});else return null;return m(b)?b:null}function p(a){try{return e(a,";")}catch(b){return""}}function q(a){return a?"string"===typeof a||"number"===typeof a:!1}
function r(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):(b="on"+b,"function"===typeof a[b]&&(c=function(a,b){return function(){a.apply(this,arguments);b.apply(this,arguments)}}(a[b],c)),a[b]=c)}function h(a,b){if(null!==a)if(a.length===+a.length)for(var c=0,f=a.length;c<f&&b.call(void 0,a[c],c,a)!=={};c++);else for(c in a)if(a.hasOwnProperty(c)&&b.call(void 0,a[c],c,a)==={})break}
function ba(a){var b=!1;h(["com","net","org","gov","edu"],function(c){a==c&&(b=!0)});return b}function s(a,b,c){var f=setInterval(function(){b()?clearInterval(f):a()},1E3*c)}function t(a,b){var c=document;try{document.createEvent?c.dispatchEvent(b):c.fireEvent(a,u)}catch(f){}}
function v(a,b){var c,f,d,g,k;c=a.length&3;f=a.length-c;d=b;for(k=0;k<f;)g=a.charCodeAt(k)&255|(a.charCodeAt(++k)&255)<<8|(a.charCodeAt(++k)&255)<<16|(a.charCodeAt(++k)&255)<<24,++k,g=3432918353*(g&65535)+((3432918353*(g>>>16)&65535)<<16)&4294967295,g=g<<15|g>>>17,g=461845907*(g&65535)+((461845907*(g>>>16)&65535)<<16)&4294967295,d^=g,d=d<<13|d>>>19,d=5*(d&65535)+((5*(d>>>16)&65535)<<16)&4294967295,d=(d&65535)+27492+(((d>>>16)+58964&65535)<<16);g=0;switch(c){case 3:g^=(a.charCodeAt(k+2)&255)<<16;case 2:g^=
(a.charCodeAt(k+1)&255)<<8;case 1:g^=a.charCodeAt(k)&255,g=3432918353*(g&65535)+((3432918353*(g>>>16)&65535)<<16)&4294967295,g=g<<15|g>>>17,d^=461845907*(g&65535)+((461845907*(g>>>16)&65535)<<16)&4294967295}d^=a.length;d^=d>>>16;d=2246822507*(d&65535)+((2246822507*(d>>>16)&65535)<<16)&4294967295;d^=d>>>13;d=3266489909*(d&65535)+((3266489909*(d>>>16)&65535)<<16)&4294967295;return(d^d>>>16)>>>0}var ca=window.CustomEvent,w;
a:{try{var da=new ca("xyzz",{detail:{foo:"bar"}});w="xyzz"===da.type&&"bar"===da.detail.foo;break a}catch(ea){}w=!1}
var fa=w?ca:"function"===typeof document.createEvent?function(a,b){try{var c=document.createEvent("CustomEvent");b?c.initCustomEvent(a,b.bubbles,b.cancelable,b.detail):c.initCustomEvent(a,!1,!1,void 0);return c}catch(f){return{}}}:"function"===typeof document.createEventObject?function(a,b){var c=document.createEventObject();c.type=a;b?(c.bubbles=Boolean(b.bubbles),c.cancelable=Boolean(b.cancelable),c.detail=b.detail):(c.bubbles=!1,c.cancelable=!1,c.detail=void 0);return c}:function(){return{}},x=
{u:null,A:null,d:void 0,C:void 0,Q:void 0,P:void 0,ea:function(){try{x.Q=x.D("__kdtv"),x.P=x.ca("__kdtv"),x.C=x.D("__kdtc"),m(x.C)&&(x.A=x.C.cid),x.aa()}catch(a){}},aa:function(){var a={},b=[];h([x.Q,x.P],function(a){m(a)&&b.push(a)});0<b.length&&(a=b[0]);for(var c=0;c<b.length;c++)"number"===typeof b[c].t&&b[c].t<=a.t&&(a=b[c]);m(a)||(a=x.ba());x.d=a;x.u=a.i},ia:function(){try{x.W("__kdtv",x.d),x.ga("_kdt",x.d),x.ha("__kdtv",x.d)}catch(a){}},D:function(a){try{var b;a:{a=a.toLowerCase();for(var c=
document.cookie.split(";"),f=0;f<c.length;f++){var d=c[f].split("=");if(d[0].trim().toLowerCase()==a){b=decodeURIComponent(1<d.length?d[1]:"");break a}}b=""}var g=n(b);return m(g)?g:null}catch(k){return null}},ca:function(a){try{if("undefined"!==typeof Storage&&"undefined"!==typeof localStorage[a]){var b=n(localStorage[a]);return m(b)?b:null}}catch(c){return null}},ba:function(){x.u=aa();x.d={};x.d.t=ga.getTime();x.d.i=x.u;return x.d},ha:function(a,b){m(b)&&(localStorage[a]=p(b))},W:function(a,b){m(b)&&
ha(a,p(b))},fa:function(a){var b=x.D("__kdtc");m(b)&&b.cid==a||(b={},b.cid=a,b.t=ga.getTime(),x.W("__kdtc",b))},ga:function(a,b){m(b)&&ha(a,'{"t":'+b.t+',"i":"'+b.i+'"}')}};
function ia(){this.J=["monospace","sans-serif","serif"];this.K=document.getElementsByTagName("body")[0];var a=this;this.N={};this.M={};var b;this.Z=function(){var a=document.createElement("span");a.style.fontSize="72px";a.style.color="#FFFFFF";a.innerHTML="mmmmmmmmmmlli";a.style.position="absolute";a.style.top="-1900px";a.style.left="-1900px";return a};this.R=function(b,f){var d=[];h(b,function(b){var c=a.Z();c.style.fontFamily=f?b+","+f:b;d.push(c);a.K.appendChild(c)});return d};this.S=function(b){h(b,
function(b){a.K.removeChild(b)});b=[]};b=this.R(this.J);h(b,function(b){var f=b.style.fontFamily;a.N[f]=b.offsetWidth;a.M[f]=b.offsetHeight});this.S(b);this.$=function(){var b="cursive;monospace;serif;sans-serif;fantasy;default;Arial;Arial Black;Arial Narrow;Arial Rounded MT Bold;Book Antiqua;Bookman Old Style;Bradley Hand ITC;Bodoni MT;Calibri;Century;Century Gothic;Casual;Comic Sans MS;Consolas;Copperplate Gothic Bold;Courier;Courier New;English Text MT;Felix Titling;Futura;Garamond;Geneva;Georgia;Gentium;Haettenschweiler;Helvetica;Impact;Jokerman;King;Kootenay;Latha;Liberation Serif;Lucida Console;Lalit;Lucida Grande;Magneto;Mistral;Modena;Monotype Corsiva;MV Boli;OCR A Extended;Onyx;Palatino Linotype;Papyrus;Parchment;Pericles;Playbill;Segoe Print;Shruti;Tahoma;TeX;Times;Times New Roman;Trebuchet MS;Verdana;Verona".split(";"),
f=[];h(a.J,function(d){var g=a.M[d],k=a.N[d];d=a.R(b,d);h(d,function(a){var b=a.style.fontFamily.split(",")[0],b=b.replace(/"/g,""),c=a.offsetHeight;a=a.offsetWidth!=k||c!=g;b&&a&&-1===f.indexOf(b)&&f.push(b)});a.S(d)});return f}}function y(a,b){if("string"!==typeof a)throw new TypeError("KondutoEvent(): type field has to be a string");this.type=a;this.value=b}window.KondutoEvent=y;
(function(){function a(a,b){t("devtoolschange",new fa("devtoolschange",{detail:{open:a,orientation:b}}))}var b={open:!1,orientation:null};setInterval(function(){var c=160<window.outerWidth-window.innerWidth,f=160<window.outerHeight-window.innerHeight,d=c?"vertical":"horizontal";window.H&&window.H.chrome&&window.H.chrome.ja||c||f?(b.open&&b.orientation===d||a(!0,d),b.open=!0,b.orientation=d):(b.open&&a(!1,null),b.open=!1,b.orientation=null)},500);"undefined"!==typeof window.module&&window.module.exports?
window.module.exports=b:window.devtools=b})();function ha(a,b){var c=new Date;c.setYear(c.getFullYear()+1);var c=a+"="+encodeURIComponent(b)+";expires="+c.toGMTString()+";path=/",f;if("undefined"!==z)f=z;else{var d=location.hostname;f=d.split(".");var g=f.length-1,k=f[g],X=ba(k),k=2==k.length;0<g&&(X||k)&&(d=[f[g-1],f[g]],!X&&1<g&&d.unshift(f[g-2]),d=d.join("."));f=z=d}document.cookie=c+(";domain="+f)}var z="undefined";
function ja(){var a="Netscape"===navigator.appName&&/Trident/.test(navigator.userAgent);return"Microsoft Internet Explorer"===navigator.appName||a}
function ka(){var a=[];window.ActiveXObject&&h("ShockwaveFlash.ShockwaveFlash;AcroPDF.PDF;PDF.PdfCtrl;QuickTime.QuickTime;rmocx.RealPlayer G2 Control;rmocx.RealPlayer G2 Control.1;RealPlayer.RealPlayer(tm) ActiveX Control (32-bit);RealVideo.RealVideo(tm) ActiveX Control (32-bit);RealPlayer;SWCtl.SWCtl;WMPlayer.OCX;AgControl.AgControl;Skype.Detection".split(";"),function(b){try{new ActiveXObject(b),a.push(b)}catch(c){}});return a}
function la(){this.A=this.B=void 0;this.I={};try{if("object"===typeof __kdt){for(var a={},b=0;b<__kdt.length;b++){var c,f;h(__kdt[b],function(b,d){"post_on_load"!==d&&(a[d]=b);"public_key"===d&&(f=b);"customer_id"===d&&q(b)&&(c=b)})}this.I=a;this.B=f;this.A=c}}catch(d){}}function A(){var a=new la;this.B=a.B;this.a=a.I;this.b="1.0"}
function ma(a){for(var b=document.getElementsByTagName("meta"),c={},f=0;f<b.length;f++){var d=b[f];d.getAttribute("name")?-1!==d.getAttribute("name").indexOf("kdt:")&&(c[d.getAttribute("name")]=d.getAttribute("content")):d.getAttribute("property")&&(c[d.getAttribute("property")]=d.getAttribute("content"))}a.v=c;return a}function B(a){var b=x;b&&"object"===typeof b&&(a.c=b.d,C(a,b.u),D(a,b.A))}function D(a,b){q(b)&&("object"===typeof a.a?a.a.customer_id=b:a.a={customer_id:b});return a}
function C(a,b){q(b)&&(a.k=b);return a}var na,E;(function(){var a=0,b,c=ma(D(C(new A,x.u),x.A));E=function(){try{if(a++,F){var b=D(c,x.A);b.w=G;b.cv=F;b.dt=I;B(b);I=F=0;l(c,"hb")}}catch(d){}};na=function(){b=(new Date).getTime();s(E,function(){return 90<((new Date).getTime()-b)/1E3},8)}})();var I=0,F=0,oa=!1,G;document.onkeydown=function(a){a=null==a?event:a;(a.ctrlKey||a.metaKey)&&86==a.keyCode&&(F+=1,oa||(oa=!0,E()))};
r(window,"devtoolschange",function(a){!0===(null==a?event:a).detail.open&&(I+=1)});(function(){var a=ja(),b=a?"focusout":"blur",c=a?document:window;r(c,a?"focusin":"focus",function(){G=!0});r(c,b,function(){G=!1})})();var J=window.Konduto?window.Konduto:new Function;function pa(a){K||(K=new A);var b=K;b.v||(b.v={});b.v["kdt:"+a.type]=a.value;B(K);l(K);K=null;return!0}
J.setCustomerID=function(a){if(!q(a))throw Error("setCustomerID(): customer id must be a number or a string");var b=!1;s(function(){L&&(b=!0)},function(){if(b){var c=new A;D(c,a);C(c,x.u);x.fa(a);l(c,"sci");x.A=a}return b},.5);return!0};window.setKondutoCustomerID=J.setCustomerID;J.getVisitorIDAsync=function(a){var b=!1;s(function(){L&&(b=!0)},function(){b&&a(x.u);return b},.5)};window.Konduto=J;var u=new fa("kondutoReady",{detail:J}),K=new A,ga=new Date,M=!0,N="",L=!1;
h(__kdt,function(a){"object"===typeof a&&(!1===a.post_on_load&&(M=!1),"string"===typeof a.public_key&&(N=a.public_key))});
try{var qa=new ia;if(!N)throw M&&O(),Error("No Konduto public key was set");if(!N.match("^[T|P][A-za-z0-9]{9}"))throw M&&O(),Error("Konduto public key format is invalid. Check our docs at: http://docs.konduto.com");navigator.userAgent.match(/chrome/i);var P=K,Q={};if(window!=window.top){Q.F="";try{var ra=document.createElement("a");Q.href=parent&&parent.document?parent.document.URL:document.referrer;Q.G=ra.search}catch(sa){Q.F="",Q.G="",Q.href=document.referrer}}else Q.referrer=document.referrer,
Q.F=document.title,Q.href=document.URL,Q.G=location.search;Q.language=navigator.language;Q.cookieEnabled=navigator.cookieEnabled;Q.da=navigator.javaEnabled();Q.platform=navigator.platform;Q.V=screen.width;Q.U=screen.height;Q.T=screen.colorDepth;var R=new Date;"object"===typeof R&&(Q.Y=R.toString());"function"===typeof R.getTimezoneOffset&&(Q.X=R.getTimezoneOffset());"number"===typeof R.getTime()&&(Q.O=R.getTime());var S=[];if("object"===typeof navigator.plugins)for(var T=0;T<navigator.plugins.length;T++){var ta=
navigator.plugins[T];S[T]=ta.name+":"+ta.description}ja()&&(S=S.concat(ka()));Q.plugins=S;var U;var V=document.createElement("canvas");if(V.getContext&&V.getContext("2d")){var W=V.getContext("2d");W.textBaseline="top";W.font="9px 'Arial'";W.textBaseline="alphabetic";W.fillStyle="#c392a1";W.fillRect(112,3,51,18);W.fillStyle="rgba(16, 175, 74, 0.002)";W.fillText("http://%TQBF.jumps.over.t.lazy.dog/?E=1&F=0",3,14);W.fillStyle="rgba(151, 210, 2, 0.002)";W.fillText("http://%TQBF.jumps.over.t.lazy.dog/?E=1&F=0",
4,20);U=V.toDataURL()}else U=null;Q.L=U;var ua=[];if(navigator.mimeTypes)for(var Y=0;Y<navigator.mimeTypes.length;Y++)navigator.mimeTypes[Y]&&ua.push(navigator.mimeTypes[Y].type);Q.mimeTypes=ua;P.e=Q.referrer;P.f=Q.F;P.g=Q.href;P.h=Q.G;Q.language&&(P.i=Q.language);P.j=Q.cookieEnabled?!0:!1;P.t=Q.da?!0:!1;Q.platform&&(P.l=Q.platform);Q.V&&(P.m=Q.V);Q.U&&(P.n=Q.U);Q.T&&(P.o=Q.T);Q.Y&&(P.p=Q.Y);Q.X&&(P.q=Q.X);Q.O&&(P.r=Q.O);if(Q.plugins){var va=0,Z=Q.plugins;Z&&"object"===typeof Z&&(P.sl=Z,va=Z.length);
P.s=va}Q.L&&(P.x=String(v(Q.L,97)));Q.mimeTypes&&(P.y=String(v(Q.mimeTypes.join(","),64)));ma(K);var wa=K,$=qa.$();if($&&"object"===typeof $){var xa=$.length;0<xa&&(wa.jf=String(v($.join(),30)));wa.jfc=xa}x.ea();x.ia();L=!0;J.sendEvent=function(a,b){switch(arguments.length){case 1:if(!(a instanceof y))throw Error("sendEvent(): requires a KondutoEvent as argument");return pa(a);case 2:if("string"!==typeof a)throw new TypeError("sendEvent(): first argument must be a string");return pa(new y(a,b))}throw Error("sendEvent(): wrong number of arguments");
};J.getVisitorID=function(){return x.u};window.getKondutoID=J.getVisitorID;u&&t("kondutoReady",u);M&&O();na()}catch(ya){}function O(){B(K);l(K);K=null};})(window,document);
